<template>

    <div>
        <load-ing :active.sync="isLoading" :can-cancel="true" :is-full-page="true"></load-ing>

        <h3>Setup Authenticator as a MFA method</h3>
        <v-card style="width: 50%;">
            <ul class="list-group">
                <li class="list-group-item">
                    <div>
                        <label><strong>STEP ONE</strong></label>
                    </div>
                    <div>
                        Download/Use any authenticator application like Google Authenticator or Okta Authenticator
                        on your mobile device.
                    </div>
                    <div>
                        <div class="form-group">
                            <select class="custom-select" id="selectService" v-model="authenticationMethod"
                                v-on:change="onSelectedAuthenticatorMethod()">
                                <option value="" selected disabled>Authenticator App</option>
                                <option v-for="method in authenticationMethodsList" :value="method.value"
                                    :key="method.name">{{
                                        method.name.toUpperCase() }}
                                </option>
                            </select>
                        </div>
                    </div>
                </li>
                <li class="list-group-item" v-if="qrCodeDataUrl">
                    <div>
                        <label><strong>STEP TWO</strong></label>
                    </div>
                    <div>
                        On your mobile device tap the "+" icon then select "Scan QR Code" to scan the QR code
                        below
                    </div>
                    <div class="m-1">
                        <div class="p-3">
                            <img :src="qrCodeDataUrl" style="border-radius: 10px; border: 1px solid grey;">

                        </div>

                    </div>
                </li>
                <li class="list-group-item" v-if="qrCodeDataUrl">
                    <div>
                        <label><strong>STEP THREE</strong></label>
                    </div>
                    <div>
                        Once the QR code has been scanned, enter the 6-digit code generated by the application.
                    </div>
                    <div class="m-1">
                        <div class="px-2 mx-1">
                            <PIN inputType="number" @pinTakenEvent="pinTakenEventHandler"></PIN>
                        </div>
                        <small v-if="error" style="color:red">{{ error }}</small>
                    </div>
                </li>
            </ul>
        </v-card>
        <div class="mt-2">
            <!-- <v-btn type="button" class="btn btn-light" @click="skip()">Skip</v-btn> -->
            <hf-buttons name="Skip" class="ml-auto" @executeAction="skip">
            </hf-buttons>
        </div>
    </div>
</template>

<script>
import PIN from './PIN.vue'
import { mapMutations, mapActions } from 'vuex/dist/vuex.common.js';
import UtilsMixin from "../../../mixins/utils";
// import EventBus from "../../../eventbus";
export default {
    name: 'SetupMfa',
    data() {
        return {
            isLoading: false,

            qrCodeDataUrl: "",
            authenticationMethodsList: [
                {
                    name: 'Google Authenticator',
                    value: 'google',
                    selected: true,
                },
                {
                    name: 'Okta Authenticator',
                    value: 'okta',
                    selected: false
                }
            ],
            authenticationMethod: "",
            error: ""
        }
    },
    components: {
        PIN
    },
    watch: {
        qrCodeDataUrl: function () {
            this.error = ""
        }
    },
    mounted() {
        console.log('Inside mounted SetupMFA.vue')
    },
    methods: {
        ...mapActions('mainStore', ['mfaGenerate', 'mfaVerify']),
        ...mapMutations('mainStore', ['setAuthToken']),

        async onSelectedAuthenticatorMethod() {
            try {
                this.isLoading = true
                const payload = {
                    authenticatorType: this.authenticationMethod
                }

                const r = await this.mfaGenerate(payload);
                this.qrCodeDataUrl = r.twoFADataUrl

                this.isLoading = false
                this.notifySuccess(`MFA Qr code generated successfully`);

            } catch (e) {
                this.isLoading = false
                this.notifyErr(e.message)
            }

        },

        async pinTakenEventHandler(pin) {
            try {
                this.isLoading = true
                const payload = {
                    authenticatorType: this.authenticationMethod,
                    twoFactorAuthenticationCode: pin
                }
                const r = await this.mfaVerify(payload)

                if (!r.isVerified) {
                    this.error = "Invalid code or expired, please try again"
                } else {
                    this.notifySuccess(`Identity verified successfully`);
                    await this.setAuthToken(r.authToken)

                    // 
                    this.$root.$emit("initializeStore", "login");

                }
                this.isLoading = false


            } catch (e) {
                this.isLoading = false
                this.notifyErr(e.message)
            }

        },

        skip() {
            this.$root.$emit("initializeStore", "login");
            // this.$root.$emit('HelloEvent', 'hi')
        }
    },
    mixins: [UtilsMixin],
}

</script>

<style scoped>
ul {
    list-style-type: none;
}
</style>